- name: Demo on Rescue
  hosts: localhost
  tasks:
    - name: Handle the error
      block:
        - name: Print a message
          ansible.builtin.debug:
            msg: 'I execute normally'

        - name: Force a failure
          ansible.builtin.shell: /bin/false

        - name: Never print this
          ansible.builtin.debug:
            msg: 'I never execute, due to the above task failing, :-('
      rescue:
        - name: this one executes if any task failure happens in block
          ansible.builtin.debug:
            msg: I caught the error, can do some stuff here to fix it :)

